### ISSUE TITLE
I still can't migrate data into my local database. Do you have that problem

### ISSUE THREAD

**Issue by maxlpy** [CSC510/SQLvsNOSQL#12]

**Comment by maxlpy** [comment]
When I run this command: mvn antrun:run -Pinit-db
It shows this error:
log4j:ERROR setFile(null,true) call failed.
java.io.FileNotFoundException: /logs/jeesite.log (No such file or directory)

And I also try use this command: mvn antrun:run -Prefresh-db. Since there is no Prefresh-db file under db file. I download a Prefresh-db file from other jeesite-master branch, it has problems too.

**Comment by jentle** [comment]
if you cannt, you don't have to load those data to make it run. You don't
even make it run, think how to create mongo dao layer into it.

the command is defined in db/init-db.bat. the ant db-unit task was defined
in pom.xml

**Comment by maxlpy** [comment]
All right.
