### ISSUE TITLE
working on service layer 

### ISSUE THREAD

**Issue by jessexu20** [CSC510/SQLvsNOSQL#18]
Please finish the CRUD in 3 service class(USER, HOUSE,REQUEST) today?

**Comment by maxlpy** [comment]
Sure, I will work on it.

**Comment by jessexu20** [comment]
have you finished it yet? without it, I cannot work on action layer.

**Comment by maxlpy** [comment]
I have finished service layer(UserService) and action layer(HouseAction and UserAction).
