### ISSUE TITLE
Should we implement service layer also as an interface?

### ISSUE THREAD

**Issue by jessexu20** [CSC510/SQLvsNOSQL#19]

**Comment by maxlpy** [comment]
I think it's a good idea, since we have same service methods and similar methods implementation between two dbs in the service.

**Comment by jessexu20** [comment]
But basically service won't know about the db things. the methods are the same, they only need to use the methods in Dao layers.

**Comment by maxlpy** [comment]
Since the methods are same, we need divide service into MDBService and SQLService. In the action layer, we can call both services.

**Comment by jessexu20** [comment]
No!! They are the same! Service layer don't need to know the db.

**Comment by maxlpy** [comment]
In that case, how to distinguish two databases?  or how to switch dbs in service?

**Comment by jessexu20** [comment]
Don't need to!  Only distinguishes the db in dao Layer.

**Comment by maxlpy** [comment]
So the same data will be inserted into two dbs at the same time?

**Comment by jessexu20** [comment]
Good question!

**Comment by jentle** [comment]
roughly build up the working  web application util now .
