### ISSUE TITLE
Do us a demo on the difference between sql and mongo

### ISSUE THREAD

**Issue by jessexu20** [CSC510/SQLvsNOSQL#21]
Figure out what kind of tests can we do to figure the differences.

**Comment by jessexu20** [comment]
Due to the weather factor, I think we should postpone the demo.  Or would you prefer to post some issues illustrating the main points, since we have not finished 30 issues yet. @CSC510/owners

**Comment by Hongyi23** [comment]
What about post my document on the google drive? @jessexu20

**Comment by jessexu20** [comment]
That’s okay! But you should still post an issue on the github illustrating the concise main idea.
