### ISSUE TITLE
Learn test techniques on Multi Thread

### ISSUE THREAD

**Issue by jessexu20** [CSC510/SQLvsNOSQL#26]
Based on your report, I think multi-thread is something we need to put into our projects. You should spend some time on it. But before that, I think you should write some simple tests on the mongo samples, as your commit is far less than us !!

@Hongyi23

**Comment by Hongyi23** [comment]
I will begin to write something based on the completed tests.

**Comment by jessexu20** [comment]
Yes! The things on my branch, please set up your own branch and use 
         git pull origin sxu11
after that you can write some tests and commit it in your own branch. we will handle the merge
