### ISSUE TITLE
I just check the document summarized by hma5, it is good but not enough. We still need more comparable points, more details and implementation methods.

### ISSUE THREAD

**Issue by maxlpy** [CSC510/SQLvsNOSQL#29]
@Hongyi23

**Comment by maxlpy** [comment]
At least 10 ~ 15 comparable points, add more details such as how and why. Add some methods that how we can test, code, or compare.

**Comment by Hongyi23** [comment]
I know they are so theoretical and we need to put them into practice by finding methods to code and test. I will start to work on it immediately after the midterm on Friday.
