### ISSUE TITLE
Focus On test

### ISSUE THREAD

**Issue by Hongyi23** [CSC510/SQLvsNOSQL#3]
Are you able to configure the hibernate part yet? If not, we'd better focus on test based on the jeesite .

You could think about the scalabilities between the two. 
The following link gives a good reference by testing performance. Generate random record using the entities and make io request
http://www.moredevs.ro/mysql-vs-mongodb-performance-benchmark/

We probably do not hold meeting this week and try to communicate via issue reports as Pro. Tim asked. Keep active as you can .

**Comment by jessexu20** [comment]
Nope! Working on jeesite then.

**Comment by Hongyi23** [comment]
you still could design your test scheme based our code.  The jeesite part will working on jgu7 branch.  I'll remain the mongodb implementation same . Once we finish the database layer, you could migrate your test case to that branch.

**Comment by jessexu20** [comment]
Okay! That sounds good! I will work on this today! and Please start a new Issue since I have closed this issue.

**Comment by jentle** [comment]
ok, we sould open issues as more as we can[?]
