### ISSUE TITLE
Change Back to Hibernate

### ISSUE THREAD

**Issue by jentle** [CSC510/SQLvsNOSQL#32]
suffered from the extreme slow performance of jdbcTemplate.I still change back to Hibernate ORM. The SQL  multi Thread part had to be further tested. And We need more test on table relations

**Comment by jessexu20** [comment]
Omg! What about the multi thread on mongo?

**Comment by jentle** [comment]
everthing still work，mongo thread is ok. Easy to Transaction

发自我的 iPhone

> 在 2015年3月23日，上午9:53，Jesse Xu <notifications@github.com> 写道：
> 
> Omg! What about the multi thread on mongo?

**Comment by jessexu20** [comment]
Great to know that. We should contribute more time to this project this
week!
