### ISSUE TITLE
Project Rubrics !!

### ISSUE THREAD

**Issue by jessexu20** [CSC510/SQLvsNOSQL#57]
Do not use the latex format .. just write in word!! @Hongyi23  
Just stick to the content discussed yesterday. But keep in mind to deal with the following.

From http://goo.gl/gmoYrk, there is a link to the report readme.
Has section: Goals
Has section: Background
Has section: Methods
Has section: Results
Has section: Discussion
Has section: Conclusion
Has section: Future Work
Has section: References
Makes the case that the result is a substantive, important, piece of work.
Contains references to other work in this area.
References are somewhat complete (&).
Defines the test procedure to be applied to the product(^).
Comments on the completeness of the tests (%).
Project's repo has dozens of files.
Project's repo has dozens to 100s of commits.
Project's repo has dozens to 100s of issue reports.
Project's repo defines six or more issue tags.
Project's repo defines three or more milestone tags.
Most of the issues use the issue tags.
Some of the issues use some of the milestone tags.
Project has no "passengers" (team members with less than 10% of the commits).
Project has no "great dictator" (a single team members with more than 75% of the commits).

**Comment by Hongyi23** [comment]
I'm writing in Word now. But it seems so hard to write as many as 10 pages...

**Comment by jessexu20** [comment]
I don't think it needs 10 pages if put on github. Just first stick to the main point in our project, left alone the others work.

**Comment by jessexu20** [comment]
Just your email and you will see that we don't need to write the 10 page paper, only write a formal doc on the github. Good news to you.

**Comment by Hongyi23** [comment]
OMG what a relief!
