### ISSUE TITLE
Compare and test

### ISSUE THREAD

**Issue by jentle** [CSC510/SQLvsNOSQL#6]
*we'll probably do not hold any meeting this week, instead using issue reporting( at least 30 next Tuesday) and show you contribution.*

Google more about what difference between the sql and nosql and how to choose, such as scalability , security, speed , flexibility . Pick a issue and working on it by test. Search -> Summary -> Focus

Open new issues or comments when you confused and reflect in your commits.

**Comment by Hongyi23** [comment]
I'm working on it!
