### ISSUE TITLE
findbyID method in BaseDao is not correct, so is deleteByid Method

### ISSUE THREAD

**Issue by jessexu20** [CSC510/SQLvsNOSQL#8]
findbyID method in BaseDao is not correct, so is deleteByid Method

it doesn't look for student id, i think.

	public T findById(Serializable id) {
		return  (T)this.mongoTemplate.findById(id, entityClass);
	}

**Comment by jentle** [comment]
It looks for id, you can get by XXX.getId(). not student id.

**Comment by jentle** [comment]
@Test
public void findById(){
User u = new User("jiang", 45);
userDao.save(u);
User u2 = userDao.findById(u.getId());
userDao.deleteById(u2.getId());
assertEquals(userDao.findById(u2.getId()),  null);
}
which proves correct

**Comment by jessexu20** [comment]
what if i would like to delete an user but I just know its student id? 
In that case, I have to first find out the user by findbyStudentID method, and then delete the user?
According to my test, it will take a very long time! more than 100 times compared to the findbyid method!
is there a better way to do this?

**Comment by jentle** [comment]
The following test does not vary much in time comsuption

@Test
public void TwoMethodFind(){
for(User u: userDao.findAll("{studentId:12}")){
userDao.delete(u);
};
 User user = new User("test",12);
userDao.save(user);
 /* Find By Object Id*/
long start = System.currentTimeMillis();
User u1 = userDao.findById(user.getId());
logger.info("findById() takes " + (System.currentTimeMillis()-start)+"ms" );
 /* Find By Student Id*/
start = System.currentTimeMillis();
User u2 = userDao.findOne("{studentId:12}");
logger.info("findOne(String) takes " +
(System.currentTimeMillis()-start)+"ms" );
 /* Find By Parameter */
Parameter parameter = new Parameter();
parameter.put("studentId", 12);
start = System.currentTimeMillis();
User u3 = userDao.findOne(parameter);
logger.info(" findOne(Parameter) takes " +
(System.currentTimeMillis()-start)+"ms" );
}

1515 [main] INFO com.webapp.dao.impl.mdb.UserMDBImplTest - findById() takes
0ms
1515 [main] INFO com.webapp.dao.impl.mdb.UserMDBImplTest - findOne(String)
takes 0ms
1531 [main] INFO com.webapp.dao.impl.mdb.UserMDBImplTest -
 findOne(Parameter) takes 0ms

**Comment by Hongyi23** [comment]
the select operation may vary when the dataset scale up to million
