### ISSUE TITLE
I don't think there should be some slides for analysis

### ISSUE THREAD

**Issue by jessexu20** [CSC510/SQLvsNOSQL#84]
As it would be covered when we are doing the talk. It is so weird to set aside analysis sections, especially separated into different section... 
The ideal one should be one person first show the test method and then the result(pic) with analysis on the same pic. 
buT WE CAN FINISH THE analysis first and left this issue for merge

@maxlpy @jentle

**Comment by maxlpy** [comment]
Yes, we can do like that.
