### ISSUE TITLE
Check my "Future Work" part

### ISSUE THREAD

**Issue by Hongyi23** [CSC510/SQLvsNOSQL#86]
More powerful hardware will be implemented, so that more large data can be used in tests, as a result of which more precise conclusion can be reached. Also, besides the JUnit Test, the front-end test will be included in our research, for the reason that it could bring more results on Multi-thread test of SQL database. What's more, the performance of other supported NoSQL database such as Cassadra will be involved.

It is OK?

**Comment by jessexu20** [comment]
You should first start with a sentence saying why we haven't done that.

**Comment by jessexu20** [comment]
Also you should note that you have misspelled the word: Cassadra which should be <b>Apache Cassandra</b>

**Comment by Hongyi23** [comment]
Like "For the restriction of time and equipment"? I see the "future work" part in the papers I found, they are simple, and give no reason why they didn't do more. @jessexu20

**Comment by jessexu20** [comment]
Yep.. just like this..those simple reason is fine!~

**Comment by jessexu20** [comment]
And probably you would like to use list to show it.
 - a
 - b
 - c

**Comment by Hongyi23** [comment]
OK I'll add it.
