### ISSUE TITLE
student uniqueness is not implemented!

### ISSUE THREAD

**Issue by jessexu20** [CSC510/SQLvsNOSQL#9]
I check the mongo db and find out that the student id is not unique, which I think I has already implemented in the previous version but that feature has not be included in this version!!
	> db.user.find()
	{ "_id" : ObjectId("54e15492fcecf644ca22dcf2"), "_class" : "com.webapp.model.User", "name" : "eee", "studentId" : 12 }
	{ "_id" : ObjectId("54e15492fcecf644ca22dcf3"), "_class" : "com.webapp.model.User", "name" : "21", "studentId" : 13 }
	{ "_id" : ObjectId("54e15492fcecf644ca22dcf4"), "_class" : "com.webapp.model.User", "name" : "2ee1", "studentId" : 133 }
	{ "_id" : ObjectId("54e15492fcecf644ca22dcf5"), "_class" : "com.webapp.model.User", "name" : "jiang", "studentId" : 12 }
	{ "_id" : ObjectId("54e15492fcecf644ca22dcf6"), "_class" : "com.webapp.model.User", "name" : "jiang", "studentId" : 13 }

**Comment by jentle** [comment]
I am not sure what is exactly the problem, but the following test pass
successfully. Try more tests.

@Test
public void unique(){
List<User> users = userDao.findAll("{studentId:12}");
for( User u : users){
userDao.delete(u);
}
 for( int i =0; i< 10; i++){
String name = "student"+i;
userDao.save(new User(name, 12));
}
 assertEquals(userDao.findAll("{studentId:12}").size(), 1);
}

**Comment by jessexu20** [comment]
which version are you using?

**Comment by jentle** [comment]
current version

**Comment by jessexu20** [comment]
On my branch? if it is on my branch, that 's right because I have done some modification by changing the model class. 
I use the annotation Indexed instead of the "Column", which is in the original version that you pushed. but  indexed annotation is only valid in mongodb.

**Comment by jentle** [comment]
it works fine with @column

发自我的 iPhone
